/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Main.Librarian;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Çağrı
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
   
    Librarian lib = new Librarian();
    
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fld_bookTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_bookAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fld_bookISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_bookPublisher = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_bookPage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fld_bookID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_bookAddClose = new javax.swing.JButton();
        btn_bookAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Kitap Adı :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        fld_bookTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Yazar Adı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 20));

        fld_bookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("ISBN :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, 20));

        fld_bookISBN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Yayınevi Adı :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 20));

        fld_bookPublisher.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Sayfa Sayısı :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, 20));

        fld_bookPage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Kitap ID :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, 20));

        fld_bookID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_book_60px_1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_bookAddClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_bookAddClose.setText("Kapat");
        btn_bookAddClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookAddCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bookAddClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 180, 50));

        btn_bookAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_bookAdd.setText("Kaydet");
        btn_bookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookAddActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bookAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookAddActionPerformed
        if (fld_bookID.getText().isEmpty() == true || fld_bookAuthor.getText().isEmpty() == true || fld_bookISBN.getText().isEmpty() == true
                || fld_bookPage.getText().isEmpty() == true || fld_bookPublisher.getText().isEmpty() == true || fld_bookTitle.getText().isEmpty() == true){
            
            JOptionPane.showMessageDialog(null, "Hata");
        }
        else{
            try {
                boolean control = lib.addBook(fld_bookID.getText(), fld_bookTitle.getText(), fld_bookAuthor.getText(), fld_bookISBN.getText(),
                        fld_bookPublisher.getText(), fld_bookPage.getText());
                if (control){
                    fld_bookAuthor.setText("");
                    fld_bookID.setText("");
                    fld_bookISBN.setText("");
                    fld_bookPage.setText("");
                    fld_bookPublisher.setText("");
                    fld_bookTitle.setText("");
                    JOptionPane.showMessageDialog(null, "İşlem Başarılı");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btn_bookAddActionPerformed

    private void btn_bookAddCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookAddCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btn_bookAddCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookAdd;
    private javax.swing.JButton btn_bookAddClose;
    private javax.swing.JTextField fld_bookAuthor;
    private javax.swing.JTextField fld_bookID;
    private javax.swing.JTextField fld_bookISBN;
    private javax.swing.JTextField fld_bookPage;
    private javax.swing.JTextField fld_bookPublisher;
    private javax.swing.JTextField fld_bookTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
