/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;
import Main.*;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Çağrı
 */
public class AddMember extends javax.swing.JFrame {

    /**
     * Creates new form AddMember
     */
    Librarian lib = new Librarian();
    public AddMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fld_addMemberLName = new javax.swing.JTextField();
        fld_addMemberUser = new javax.swing.JTextField();
        fld_addMemberPosta = new javax.swing.JTextField();
        fld_addMemberFName = new javax.swing.JTextField();
        fld_addMemberPass = new javax.swing.JPasswordField();
        lbl_addMemberBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_addMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Soyadı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Şifre :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Kullanıcı Adı :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("E-posta Adresi :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Ad :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 30));

        fld_addMemberLName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_addMemberLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 30));

        fld_addMemberUser.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_addMemberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 240, 30));

        fld_addMemberPosta.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_addMemberPosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 240, 30));

        fld_addMemberFName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_addMemberFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));

        fld_addMemberPass.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_addMemberPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 240, 30));

        lbl_addMemberBack.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_addMemberBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addMemberBack.setText("Girişe geri dön");
        lbl_addMemberBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addMemberBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addMemberBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addMemberBackMouseExited(evt);
            }
        });
        jPanel1.add(lbl_addMemberBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_male_52px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btn_addMember.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_addMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_male_30px.png"))); // NOI18N
        btn_addMember.setText("        Kaydet");
        btn_addMember.setHideActionText(true);
        btn_addMember.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addMemberActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_addMemberBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMemberBackMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_addMemberBackMouseClicked

    private void lbl_addMemberBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMemberBackMouseEntered
        setColor(lbl_addMemberBack);
    }//GEN-LAST:event_lbl_addMemberBackMouseEntered

    private void lbl_addMemberBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMemberBackMouseExited
        resetColor(lbl_addMemberBack);
    }//GEN-LAST:event_lbl_addMemberBackMouseExited

    private void btn_addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addMemberActionPerformed
        if (fld_addMemberFName.getText().length() == 0 || fld_addMemberLName.getText().length() == 0 || fld_addMemberUser.getText().length() == 0
                || fld_addMemberPosta.getText().length() == 0 || fld_addMemberPass.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Tüm alanları doldurunuz.");
        }
        else{
            try {
                boolean control = lib.addMember(fld_addMemberFName.getText(), fld_addMemberLName.getText(), fld_addMemberUser.getText(), fld_addMemberPosta.getText()
                        ,fld_addMemberPass.getText());
                if (control){
                    fld_addMemberFName.setText("");
                    fld_addMemberLName.setText("");
                    fld_addMemberPass.setText("");
                    fld_addMemberPosta.setText("");
                    fld_addMemberUser.setText("");
                    
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btn_addMemberActionPerformed

    public void setColor(JLabel label){
        label.setForeground(new java.awt.Color(115,163,239));
    } 
    
    public void resetColor(JLabel label){
        label.setForeground(new java.awt.Color(0,0,0));
    } 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addMember;
    private javax.swing.JTextField fld_addMemberFName;
    private javax.swing.JTextField fld_addMemberLName;
    private javax.swing.JPasswordField fld_addMemberPass;
    private javax.swing.JTextField fld_addMemberPosta;
    private javax.swing.JTextField fld_addMemberUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_addMemberBack;
    // End of variables declaration//GEN-END:variables
}
