/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Helper.DBConnect;
import Main.Librarian;
import Main.Member;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Çağrı
 */
public class Borrow extends javax.swing.JFrame {

    /**
     * Creates new form Borrow
     */
    
    Statement st = null;
    ResultSet rs = null;
    DBConnect conn = new DBConnect();
    Connection con = conn.connectDB();
    PreparedStatement pst = null;
    Librarian lib = new Librarian();
    private DefaultTableModel bookTable = null;
    private Object [] bookData = null;
    private String [] memberData = null;
    Member member = new Member();
    JTableHeader header = null;
    EditBook ob = new EditBook();
   
    
    public Borrow() throws SQLException{
        initComponents();
        ob.listed(table_borrowBook);
        edit();
        table_borrowBook.setRowHeight(25);
        colFont();
    }
    
    private void edit(){
        if(member.getMemberID() > 0 ){
            fld_borrowID.setText(Integer.toString(member.getMemberID()));
            fld_borrowID.setEditable(false);
        }
    }
    
    private void selected(){
        int i = table_borrowBook.getSelectedRow();
        TableModel model = table_borrowBook.getModel();
        fld_borrowBookID.setText(model.getValueAt(i, 0).toString());
        fld_borrowBookTitle.setText(model.getValueAt(i, 1).toString());
        fld_borrowBookAuthor.setText(model.getValueAt(i, 2).toString());
        fld_borrowBookISBN.setText(model.getValueAt(i, 3).toString());
        fld_borrowBookPublisher.setText(model.getValueAt(i, 4).toString());
        fld_borrowBookPage.setText(model.getValueAt(i, 5).toString());
    }
    
    private void colFont(){
        header = table_borrowBook.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16) {
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fld_borrowID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fld_borrowBookTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_borrowBookAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fld_borrowBookISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_borrowBookPublisher = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_borrowBookPage = new javax.swing.JTextField();
        btn_borrowClose = new javax.swing.JButton();
        btn_borrowBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fld_borrowBookID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        issue_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_borrowBook = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Kitap ID :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, 20));

        fld_borrowID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Kitap Adı :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 20));

        fld_borrowBookTitle.setEditable(false);
        fld_borrowBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Yazar Adı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 20));

        fld_borrowBookAuthor.setEditable(false);
        fld_borrowBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("ISBN :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 80, 20));

        fld_borrowBookISBN.setEditable(false);
        fld_borrowBookISBN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Yayınevi Adı :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 110, 20));

        fld_borrowBookPublisher.setEditable(false);
        fld_borrowBookPublisher.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Sayfa Sayısı :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 110, 20));

        fld_borrowBookPage.setEditable(false);
        fld_borrowBookPage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 250, 30));

        btn_borrowClose.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_borrowClose.setText("Geri Dön");
        btn_borrowClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrowCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_borrowClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 140, 50));

        btn_borrowBook.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_borrowBook.setText("Ödünç Al");
        btn_borrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrowBookActionPerformed(evt);
            }
        });
        jPanel1.add(btn_borrowBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 140, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kullanıcı ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 40));

        fld_borrowBookID.setEditable(false);
        fld_borrowBookID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_borrowBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 250, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_people_64px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        issue_date.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(issue_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel8.setText("Tarih :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 130, 30));

        table_borrowBook.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        table_borrowBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap ID", "Kitap Adı", "Kitap Yazarı", "ISBN", "Yayınevi", "Sayfa Sayısı"
            }
        ));
        table_borrowBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_borrowBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_borrowBook);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1100, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_borrowBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_borrowBookMouseClicked
        selected();
    }//GEN-LAST:event_table_borrowBookMouseClicked

    private void btn_borrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrowBookActionPerformed
        
        if (fld_borrowBookAuthor.getText().length() == 0 || fld_borrowBookID.getText().length() == 0 || fld_borrowBookISBN.getText().length() == 0 ||
                fld_borrowBookPage.getText().length() == 0 || fld_borrowBookPublisher.getText().length() == 0 || fld_borrowBookTitle.getText().length() == 0 ||
                fld_borrowID.getText().length() == 0 || issue_date.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "Boş Alan Bırakmayınız.");
        }
        
        else{
            int selectBorrowID = Integer.parseInt(fld_borrowID.getText());
            memberData = new String[2];
        
        try {
            
            String query = "SELECT * FROM member WHERE id = " + selectBorrowID;
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            if (rs.next() == true) {
                memberData [0] = rs.getObject(2).toString();
                memberData [1] = rs.getObject(3).toString();
                String selectID = fld_borrowBookID.getText();
                String selectTitle = fld_borrowBookTitle.getText();
                String selectAuthor = fld_borrowBookAuthor.getText();
                String selectISBN = fld_borrowBookISBN.getText();
                String selectPublisher = fld_borrowBookPublisher.getText();
                String selectPage = fld_borrowBookPage.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(issue_date.getDate());
                
            
            boolean control = lib.borrowBook(selectBorrowID, memberData [0], memberData [1], selectID, selectTitle, selectAuthor, selectISBN, selectPublisher, selectPage, date);
                if (control) {
                    lib.deleteBook(fld_borrowBookID.getText());
                    ob.update(table_borrowBook);
                    fld_borrowBookAuthor.setText("");
                    fld_borrowBookID.setText("");
                    fld_borrowBookISBN.setText("");
                    fld_borrowBookPage.setText("");
                    fld_borrowBookPublisher.setText("");
                    fld_borrowBookTitle.setText("");
                    issue_date.setDate(null);
                    JOptionPane.showMessageDialog(null, "İşlem Başarılı");
                    
                }
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Böyle Bir Kullanıcı Sisteme Kayıtlı Değil..");
            }
          
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
        
        
        
        
        
        
    }//GEN-LAST:event_btn_borrowBookActionPerformed

    private void btn_borrowCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrowCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btn_borrowCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                try {
                    new Borrow().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrowBook;
    private javax.swing.JButton btn_borrowClose;
    private javax.swing.JTextField fld_borrowBookAuthor;
    private javax.swing.JTextField fld_borrowBookID;
    private javax.swing.JTextField fld_borrowBookISBN;
    private javax.swing.JTextField fld_borrowBookPage;
    private javax.swing.JTextField fld_borrowBookPublisher;
    private javax.swing.JTextField fld_borrowBookTitle;
    private javax.swing.JTextField fld_borrowID;
    private com.toedter.calendar.JDateChooser issue_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_borrowBook;
    // End of variables declaration//GEN-END:variables
}
