/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Helper.Win10UI;
import Main.Librarian;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Çağrı
 */
public class EditBook extends javax.swing.JFrame {

    /**
     * Creates new form EditBook
     */
    private final Win10UI modernUI = new Win10UI();
    static Librarian lib = new Librarian();
    private DefaultTableModel bookTable = null;
    private Object [] bookData = null;
    private JTableHeader header = null;
    
    public EditBook() throws SQLException{
        modernUI.modernDesign();
        initComponents();
        listed(table_editBook);
        table_editBook.setRowHeight(25);
        colFont();
    }
    
    private void colFont(){
        header = table_editBook.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16) {
        });
    }
    
    final void listed(JTable table) throws SQLException{
        bookTable = (DefaultTableModel) table.getModel();
        Object [] colBookName = new Object[6];
        colBookName[0] = "Kitap ID";
        colBookName[1] = "Kitap Adı";
        colBookName[2] = "Kitap Yazarı";
        colBookName[3] = "ISBN";
        colBookName[4] = "Yayınevi";
        colBookName[5] = "Sayfa Sayısı";
        bookTable.setColumnIdentifiers(colBookName);
        bookData = new Object[6];
        for (int i = 0; i < lib.getBookList().size(); i++) {
            bookData[0] = lib.getBookList().get(i).getBookID();
            bookData[1] = lib.getBookList().get(i).getBookTitle();
            bookData[2] = lib.getBookList().get(i).getBookAuthor();
            bookData[3] = lib.getBookList().get(i).getBookISBN();
            bookData[4] = lib.getBookList().get(i).getBookPublisher();
            bookData[5] = lib.getBookList().get(i).getBookPage();
            bookTable.addRow(bookData);
           
           
        }
    }
    
    public void update(JTable table) throws SQLException{
        DefaultTableModel updateTable = (DefaultTableModel) table.getModel();
        updateTable.setRowCount(0);
        for (int i = 0; i < lib.getBookList().size(); i++) {
            bookData[0] = lib.getBookList().get(i).getBookID();
            bookData[1] = lib.getBookList().get(i).getBookTitle();
            bookData[2] = lib.getBookList().get(i).getBookAuthor();
            bookData[3] = lib.getBookList().get(i).getBookISBN();
            bookData[4] = lib.getBookList().get(i).getBookPublisher();
            bookData[5] = lib.getBookList().get(i).getBookPage();
            bookTable.addRow(bookData);
           
        }
    }

    private void selected(){
        int i = table_editBook.getSelectedRow();
        TableModel model = table_editBook.getModel();
        fld_editBookID.setText(model.getValueAt(i, 0).toString());
        fld_editBookTitle.setText(model.getValueAt(i, 1).toString());
        fld_editBookAuthor.setText(model.getValueAt(i, 2).toString());
        fld_editBookISBN.setText(model.getValueAt(i, 3).toString());
        fld_editBookPublisher.setText(model.getValueAt(i, 4).toString());
        fld_editBookPage.setText(model.getValueAt(i, 5).toString());
    }
    
    private void clear(){
        fld_editBookAuthor.setText("");
        fld_editBookID.setText("");
        fld_editBookISBN.setText("");
        fld_editBookPage.setText("");
        fld_editBookPublisher.setText("");
        fld_editBookTitle.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fld_editBookID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fld_editBookTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_editBookAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fld_editBookISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_editBookPublisher = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_editBookPage = new javax.swing.JTextField();
        btn_editBookClose = new javax.swing.JButton();
        btn_editBookUpdate = new javax.swing.JButton();
        btn_editBookDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_editBook = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Kitap ID :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 20));

        fld_editBookID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 250, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Kitap Adı :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        fld_editBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Yazar Adı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        fld_editBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("ISBN :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 80, 20));

        fld_editBookISBN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Yayınevi Adı :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 110, 20));

        fld_editBookPublisher.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Sayfa Sayısı :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 110, 20));

        fld_editBookPage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editBookPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 250, 30));

        btn_editBookClose.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editBookClose.setText("Geri Dön");
        btn_editBookClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editBookCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editBookClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 140, 50));

        btn_editBookUpdate.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editBookUpdate.setText("Güncelle");
        btn_editBookUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editBookUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editBookUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, 50));

        btn_editBookDelete.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editBookDelete.setText("Sil");
        btn_editBookDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editBookDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editBookDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 140, 50));

        table_editBook.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        table_editBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap ID", "Kitap Adı", "Kitap Yazarı", "ISBN", "Yayınevi", "Sayfa Sayısı"
            }
        ));
        table_editBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_editBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_editBook);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1100, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_editBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_editBookMouseClicked
        selected();
    }//GEN-LAST:event_table_editBookMouseClicked

    private void btn_editBookUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editBookUpdateActionPerformed
        if (fld_editBookID.getText().isEmpty() == true || fld_editBookAuthor.getText().isEmpty() == true || fld_editBookISBN.getText().isEmpty() == true
                || fld_editBookPage.getText().isEmpty() == true || fld_editBookPublisher.getText().isEmpty() == true || fld_editBookTitle.getText().isEmpty() == true){
            
            JOptionPane.showMessageDialog(null, "Hata");
        }
        else{
            int i = table_editBook.getSelectedRow();
            String selectID = fld_editBookID.getText();
            String selectTitle = fld_editBookTitle.getText();
            String selectAuthor = fld_editBookAuthor.getText();
            String selectISBN = fld_editBookISBN.getText();
            String selectPublisher = fld_editBookPublisher.getText();
            String selectPage = fld_editBookPage.getText();
            
            try {
                
                boolean control=lib.updateBook(selectID, selectTitle, selectAuthor, selectISBN, selectPublisher, selectPage);
                update(table_editBook);
                if(control){
                    clear();
                    JOptionPane.showMessageDialog(null, "işlem başarılı");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_editBookUpdateActionPerformed

    private void btn_editBookDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editBookDeleteActionPerformed
        if (fld_editBookID.getText().isEmpty() == true || fld_editBookAuthor.getText().isEmpty() == true || fld_editBookISBN.getText().isEmpty() == true
                || fld_editBookPage.getText().isEmpty() == true || fld_editBookPublisher.getText().isEmpty() == true || fld_editBookTitle.getText().isEmpty() == true){
            
            JOptionPane.showMessageDialog(null, "Hata");
        }
        else{
            try {
                boolean control = lib.deleteBook(fld_editBookID.getText());
                update(table_editBook);
                if (control){
                    clear();
                    JOptionPane.showMessageDialog(null, "İşlem Başarılı");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btn_editBookDeleteActionPerformed

    private void btn_editBookCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editBookCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btn_editBookCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditBook().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editBookClose;
    private javax.swing.JButton btn_editBookDelete;
    private javax.swing.JButton btn_editBookUpdate;
    private javax.swing.JTextField fld_editBookAuthor;
    private javax.swing.JTextField fld_editBookID;
    private javax.swing.JTextField fld_editBookISBN;
    private javax.swing.JTextField fld_editBookPage;
    private javax.swing.JTextField fld_editBookPublisher;
    private javax.swing.JTextField fld_editBookTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_editBook;
    // End of variables declaration//GEN-END:variables
}
