/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Main.Librarian;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Çağrı
 */
public class EditMember extends javax.swing.JFrame {

    /**
     * Creates new form EditMember
     */
    Librarian lib = new Librarian();
    private DefaultTableModel memberTable = null;
    private Object [] memberData = null;
    private JTableHeader header = null;
    
    public EditMember() throws SQLException {
        initComponents();
        listed();
        table_editMember.setRowHeight(25);
        colFont();
    }
    
    private void colFont(){
        header = table_editMember.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16) {
        });
    }
    
    private void listed() throws SQLException{
        memberTable = (DefaultTableModel) table_editMember.getModel();
        Object [] colMemberName = new Object[6];
        colMemberName [0] = "ID";
        colMemberName [1] = "Kullanıcı Ad";
        colMemberName [2] = "Kullanıcı Soyad";
        colMemberName [3] = "Username";
        colMemberName [4] = "E-posta";
        colMemberName [5] = "Şifre";
        memberTable.setColumnIdentifiers(colMemberName);
        memberData = new Object[6];
        for (int i = 0; i < lib.getMemberList().size(); i++) {
            memberData [0] = lib.getMemberList().get(i).getId();
            memberData [1] = lib.getMemberList().get(i).getName();
            memberData [2] = lib.getMemberList().get(i).getLastName();
            memberData [3] = lib.getMemberList().get(i).getUsername();
            memberData [4] = lib.getMemberList().get(i).getPosta();
            memberData [5] = lib.getMemberList().get(i).getPassword();
            memberTable.addRow(memberData);
            
        }
    }
    
    private void update() throws SQLException{
        DefaultTableModel updateTable = (DefaultTableModel) table_editMember.getModel();
        updateTable.setRowCount(0);
        for (int i = 0; i < lib.getMemberList().size(); i++) {
            memberData [0] = lib.getMemberList().get(i).getId();
            memberData [1] = lib.getMemberList().get(i).getName();
            memberData [2] = lib.getMemberList().get(i).getLastName();
            memberData [3] = lib.getMemberList().get(i).getUsername();
            memberData [4] = lib.getMemberList().get(i).getPosta();
            memberData [5] = lib.getMemberList().get(i).getPassword();
            memberTable.addRow(memberData);
        
        }
    }
    
    private void selected(){
        int i = table_editMember.getSelectedRow();
        TableModel model = table_editMember.getModel();
        fld_editMemberID.setText(model.getValueAt(i, 0).toString());
        fld_editMemberFName.setText(model.getValueAt(i, 1).toString());
        fld_editMemberLName.setText(model.getValueAt(i, 2).toString());
        fld_editMemberUser.setText(model.getValueAt(i, 3).toString());
        fld_editMemberPosta.setText(model.getValueAt(i, 4).toString());
        fld_editMemberPass.setText(model.getValueAt(i, 5).toString());
    }
    
    private void clear(){
        fld_editMemberFName.setText("");
        fld_editMemberID.setText("");
        fld_editMemberLName.setText("");
        fld_editMemberPass.setText("");
        fld_editMemberPosta.setText("");
        fld_editMemberUser.setText("");
    }
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fld_editMemberID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fld_editMemberFName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_editMemberLName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fld_editMemberUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fld_editMemberPosta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fld_editMemberPass = new javax.swing.JTextField();
        btn_editMemberUpdate = new javax.swing.JButton();
        btn_editMemberDelete = new javax.swing.JButton();
        btn_editMemberClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_editMember = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Kullanıcı ID :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 20));

        fld_editMemberID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 250, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Kullanıcı Ad :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        fld_editMemberFName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Kullanıcı Soyadı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        fld_editMemberLName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Username :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 100, 20));

        fld_editMemberUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("E - posta :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 110, 20));

        fld_editMemberPosta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberPosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Şifre :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 110, 20));

        fld_editMemberPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(fld_editMemberPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 250, 30));

        btn_editMemberUpdate.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editMemberUpdate.setText("Güncelle");
        btn_editMemberUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editMemberUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editMemberUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 140, 50));

        btn_editMemberDelete.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editMemberDelete.setText("Sil");
        btn_editMemberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editMemberDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editMemberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 140, 50));

        btn_editMemberClose.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_editMemberClose.setText("Geri Dön");
        btn_editMemberClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editMemberCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editMemberClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 140, 50));

        table_editMember.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        table_editMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kullanıcı Ad", "Kullanıcı Soyad", "Username", "E-posta", "Şifre"
            }
        ));
        table_editMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_editMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_editMember);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1100, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editMemberUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editMemberUpdateActionPerformed
        if (fld_editMemberFName.getText().length() == 0 || fld_editMemberLName.getText().length() == 0 || fld_editMemberUser.getText().length() == 0
                || fld_editMemberPosta.getText().length() == 0 || fld_editMemberPass.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Tüm alanları doldurunuz.");
        }
        else{
            int i = table_editMember.getSelectedRow();
            int selectID = Integer.parseInt(fld_editMemberID.getText());
            String selectFName = fld_editMemberFName.getText();
            String selectLName = fld_editMemberLName.getText();
            String selectUser = fld_editMemberUser.getText();
            String selectPosta = fld_editMemberPosta.getText();
            String selectPass = fld_editMemberPass.getText();
            
            try {
                
                boolean control = lib.updateMember(selectID, selectFName, selectLName , selectUser, selectPosta, selectPass);
                update();
                if(control){
                    clear();
                    JOptionPane.showMessageDialog(null, "işlem başarılı");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_editMemberUpdateActionPerformed

    private void btn_editMemberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editMemberDeleteActionPerformed
         if (fld_editMemberFName.getText().length() == 0 || fld_editMemberLName.getText().length() == 0 || fld_editMemberUser.getText().length() == 0
                || fld_editMemberPosta.getText().length() == 0 || fld_editMemberPass.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Tüm alanları doldurunuz.");
        }
         else{
             try {
                int i = table_editMember.getSelectedRow();
                String value = table_editMember.getModel().getValueAt(i, 0).toString();
                boolean control = lib.deleteMember(Integer.parseInt(fld_editMemberID.getText()));
                update();
                if (control){
                    clear();
                    JOptionPane.showMessageDialog(null, "İşlem Başarılı");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
         }
    }//GEN-LAST:event_btn_editMemberDeleteActionPerformed

    private void table_editMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_editMemberMouseClicked
        selected();
    }//GEN-LAST:event_table_editMemberMouseClicked

    private void btn_editMemberCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editMemberCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btn_editMemberCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditMember().setVisible(true);
                } catch (SQLException ex) {
                   
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editMemberClose;
    private javax.swing.JButton btn_editMemberDelete;
    private javax.swing.JButton btn_editMemberUpdate;
    private javax.swing.JTextField fld_editMemberFName;
    private javax.swing.JTextField fld_editMemberID;
    private javax.swing.JTextField fld_editMemberLName;
    private javax.swing.JTextField fld_editMemberPass;
    private javax.swing.JTextField fld_editMemberPosta;
    private javax.swing.JTextField fld_editMemberUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_editMember;
    // End of variables declaration//GEN-END:variables
}
