/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Helper.*;
import Main.Librarian;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Çağrı
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    private Win10UI modernUI = new Win10UI();
    Librarian lib = new Librarian();
    public Register() {
        modernUI.modernDesign();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fld_ogrSoyad = new javax.swing.JTextField();
        fld_ogrUser = new javax.swing.JTextField();
        fld_ogrPosta = new javax.swing.JTextField();
        fld_ogrAd = new javax.swing.JTextField();
        fld_ogrPass = new javax.swing.JPasswordField();
        lbl_ogrBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_ogrRegister1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Soyadı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Şifre :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Kullanıcı Adı :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("E-posta Adresi :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Ad :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 30));

        fld_ogrSoyad.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_ogrSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 30));

        fld_ogrUser.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_ogrUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 240, 30));

        fld_ogrPosta.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_ogrPosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 240, 30));

        fld_ogrAd.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_ogrAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));

        fld_ogrPass.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(fld_ogrPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 240, 30));

        lbl_ogrBack.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_ogrBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ogrBack.setText("Girişe geri dön");
        lbl_ogrBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ogrBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ogrBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ogrBackMouseExited(evt);
            }
        });
        jPanel1.add(lbl_ogrBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_male_52px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btn_ogrRegister1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_ogrRegister1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_male_30px.png"))); // NOI18N
        btn_ogrRegister1.setText("       Kayıt Ol");
        btn_ogrRegister1.setHideActionText(true);
        btn_ogrRegister1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_ogrRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogrRegister1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ogrRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ogrBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ogrBackMouseEntered
        setColor(lbl_ogrBack);
    }//GEN-LAST:event_lbl_ogrBackMouseEntered

    private void lbl_ogrBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ogrBackMouseExited
        resetColor(lbl_ogrBack);
    }//GEN-LAST:event_lbl_ogrBackMouseExited

    private void lbl_ogrBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ogrBackMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_ogrBackMouseClicked

    private void btn_ogrRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogrRegister1ActionPerformed
        if (fld_ogrAd.getText().length() == 0 || fld_ogrSoyad.getText().length() == 0 || fld_ogrUser.getText().length() == 0
                || fld_ogrPosta.getText().length() == 0 || fld_ogrPass.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Tüm alanları doldurunuz.");
        }
        else{
            try {
                boolean control = lib.addMember(fld_ogrAd.getText(), fld_ogrSoyad.getText(), fld_ogrUser.getText(), fld_ogrPosta.getText()
                        ,fld_ogrPass.getText());
                if (control){
                    fld_ogrAd.setText("");
                    fld_ogrPass.setText("");
                    fld_ogrPosta.setText("");
                    fld_ogrSoyad.setText("");
                    fld_ogrUser.setText("");
                    JOptionPane.showMessageDialog(null, "İşlem Başarılı");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btn_ogrRegister1ActionPerformed

    public void setColor(JLabel label){
        label.setForeground(new java.awt.Color(115,163,239));
    } 
    
    public void resetColor(JLabel label){
        label.setForeground(new java.awt.Color(0,0,0));
    } 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ogrRegister1;
    private javax.swing.JTextField fld_ogrAd;
    private javax.swing.JPasswordField fld_ogrPass;
    private javax.swing.JTextField fld_ogrPosta;
    private javax.swing.JTextField fld_ogrSoyad;
    private javax.swing.JTextField fld_ogrUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ogrBack;
    // End of variables declaration//GEN-END:variables
}
